### ISSUE TITLE
Des d'ahir no es veu res

### ISSUE THREAD

**Issue by juanmah** [jqandreu/plugin.video.tv3.cat#10]

**Comment by juanmah** [comment]
He provat en android i en linux, amb els mateixos resultats.

**Comment by Shut3n** [comment]
El mateix a mi, linux i android. Navega per les llistes, pero dona error al seleccionar el video. El complement demana l'informació de enregistrament, pero no dispossa d'accés a configuració per indicar l'usuario i contrasenya del servei. Algú canvi de tv3 en l'acces de la web?

**Comment by jqandreu** [comment]
Ja està solucionat el fall. Hi havia alguns canvis en el codi del servidor. El darrer commit de Github té la darrera vesió corregida. Queda pendent d'enviar al repositori oficial de Kodi

**Comment by Shut3n** [comment]
Moltes gràcies

**Comment by oriol78** [comment]
hola perdo soc nou que hem de fer per tornar a veure al kodi tv3

**Comment by jqandreu** [comment]
Hola. Pots descarregar el zip des d'aqui i instalar-lo des de Kodi. Encara no he pogut enviar el plugin al repositori oficial

**Comment by oriol78** [comment]
desde on el puc descarregar?

**Comment by jqandreu** [comment]
Des de la web https://github.com/jqandreu/plugin.video.tv3.cat. A la dreta hi un buto "Clone or download". Clicant a la flexta es desplega i apareix la opció "Download zip"

**Comment by oriol78** [comment]
moltes gracies i perdo que es el primer cop que entru a una pagina aixi

**Comment by mlforcada** [comment]
Moltes gràcies, funciona perfecte! Esperem que aparega prompte en el repositori oficial!

**Comment by jqandreu** [comment]
Han canviat el sistema per enviar els plugins al repositori oficial. Estic tenint alguns problemes per enviar-lo però espero tenir-ho solucionat els pròxims dies

**Comment by kusinkay** [comment]
Gràcies @jqandreu 
Ets un crack!
Jo vull ser com tu quan sigui gran

**Comment by jqandreu** [comment]
Gràcies!

**Comment by jqandreu** [comment]
Ja està disponible al repositori oficial la darrera versió

**Comment by kusinkay** [comment]
També descarregat amb èxit des de repositori.
Molt bona feina @jqandreu

**Comment by jqandreu** [comment]
Moltes gràcies
