### ISSUE TITLE
problemes amb accés a programes

### ISSUE THREAD

**Issue by mjjofre** [jqandreu/plugin.video.tv3.cat#11]
Bon dia,
Felicitats per la meravellosa feina feta. 
He instal.lat el complement amb la versió que recomanes descarregar en aquesta mateixa plana. Les seccions inicials apareixen perfectes però, a les llistes de programes en accedir no apareix cap enllaç.
Potser hi ha nous canvis al servidor? CUlpa meva?
Comentari amb finalitat informativa. Tenim paciència, anirem provant, Gràcies de nou

**Comment by jqandreu** [comment]
Moltes gràcies. La versió que funciona bé és el commit del 16 de març. Posteriorment vaig pujar una altra versió pero encara no està del tot acabat. Aquests dies ho acabaré i el pujaré al repositori oficial

**Comment by mjjofre** [comment]
Gràcies!

Emocionada d'haver rebut resposta.

Entenc, doncs, que el que haig de fer és esperar la nova versió al
repositori.

Felicitats de nou per la feina. Malgrat les compatibilitats amb chromecast,
el teu complement és l'opció amb millor qualitat de video.

Salutacions,

MJ

El dl., 26 de març 2018, 15:16, jqandreu <notifications@github.com> va
escriure:

**Comment by jqandreu** [comment]
Pots descarregar el zip que conté la versió 1.3.8 des de la pagina https://github.com/jqandreu/plugin.video.tv3.cat/tree/104bd492be4d3b278318008632c34caf578d5a9e

Pulsant al buto "clone or download" y despres a "Download zip" per descarregar el zip amb la versió que funciona

**Comment by jqandreu** [comment]
Ja està publicada al repositori la versió que funciona correctament

**Comment by mjjofre** [comment]
Moltes gràcies.
Ara mateix actualitzo.
Abraçada d'una fan.


El dj., 5 d’abr. 2018, 19:12, jqandreu <notifications@github.com> va
escriure:
