### ISSUE TITLE
Canals "normals" no funcionen al extranger pero desde la web si.

### ISSUE THREAD

**Issue by jagjordi** [jqandreu/plugin.video.tv3.cat#12]
Hola, 
Primer gràcies pel fantàstic addon.
Des de Suècia, he detectat que els canals normals no funcionen tot i que per internet (ccma.cat/tv3/directe/tv3/) sí que es pot veure correctament. He provat també amb una VPN connectada a Espanya però el resultat és el mateix. La versió internacional sí que funciona.
Alguna pista sobre perquè no funciona?
Salutacions

**Comment by jqandreu** [comment]
Moltes gràcies. Disculpes per haver tardat tant en respondre
Suposo que et refereixes als canals  d'emissió internacional. A l'apartat de canals en directe hi ha entrades per veure els canals des de Catalunya i entrades per veure els canals des de fora (emissió internacional.

Pots provar aquest dos links des de VLC o algun reproductor semblant?

https://ccma-tva-int-cellnex-live-hls.secure.footprint.net/int/ngrp:tv3_web/playlist.m3u8
http://ccma-tva-int-cellnex-live-hls.secure.footprint.net/int/ngrp:tv3_web/playlist.m3u8

El primer, amb https, és el que s'utilitza ara a la web i el segon, amb http, és el que utilitza el plugin. Els he provat tots dos i a mi em funcionen els dos, també amb una VPN des de Suecia

Salutacions

**Comment by jagjordi** [comment]
Gràcies!
Em refereixo que des del plugin els canals internacionals funcionen però els "ordinaris" no.
He provat els dos links i funcionen els dos des de VLC.
Salutacions
