### ISSUE TITLE
Ha deixat de funcionar

### ISSUE THREAD

**Issue by Roofbreaker** [jqandreu/plugin.video.tv3.cat#13]
Des de fa uns dies es pot navegar per les llistes però no apareix cap programa o episodi i per tant no es pot veure res

**Comment by jqandreu** [comment]
A mi amb Kodi 17.6 i Libreelec em funciona be. Quina versió tens i quin sistema operatiu?

**Comment by kusinkay** [comment]
Kodi 17.6
Ubuntu 14.04
I em passa el mateix que diu @Roofbreaker 

Moltes gràcies

**Comment by kusinkay** [comment]
Veig aquests logs, no se si pot ajudar

5:18:24.566 T:3032177152   ERROR: GetDirectory - Error getting plugin://plugin.video.tv3.cat/?mode=destaquem&name=Avui%20destaquem&url
15:18:24.567 T:3032177152   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tv3.cat/?mode=destaquem&name=Avui%20destaquem&url) failed

**Comment by Roofbreaker** [comment]
Hola

El meus sistema:
   Kodi 17.6 (14 novembre 2017)
   Ubuntu 14.04.5 LTS (kernel : linux 3.13.0-66-generic)

Gràcies

**Comment by jofrep** [comment]
Hola,
Jo vaig servir la versió 1.3.9
Kodi 15.2
Ubuntu 16.04.5 LTS

i funciona bé
Salut

**Comment by Roofbreaker** [comment]
Hola

He oblidat indicar la versió del pluggin, és la 1.3.9.

Sembla que el que tenim en comú Kusinkay i jo és la versió 14.04 d'Ubuntu mentrés que Jofrep, amb la versió 16.04, no té problemes. Probaré a actualitzar Ubuntu a aquesta versió i ja us diré.

Gràcies

**Comment by Roofbreaker** [comment]
Confirmat, la versio del pluggin 1.3.9 funciona bé després d'actualitzar Ubuntu a 18.04

Gràcies

**Comment by jqandreu** [comment]
Per tant tanco la incidència. Moltes gràcies
