### ISSUE TITLE
No puc mirar el programa Les de l'hoquei

### ISSUE THREAD

**Issue by Azertixe** [jqandreu/plugin.video.tv3.cat#15]
Bondia. Miro emissions des de França mitjançant la teva extensió. Moltes gràcies a tu 👍🏼
Els altres programes semblen funcionar normalment però no puc visionar Les de l'hoquei.
Gràcies per la teva feina 🙏🏼

**Comment by jofrep** [comment]
Hola. "Les de l'hoquei" només es pot veure fora de Catalunya en directe. Els videos del 3 a la carta de l "Les de l'hoquei " no es poden veure des de fora. No és un problema de la aplicació sino de restriccions de TV3 (entenc que per drets i acords mal pensats).

**Comment by Azertixe** [comment]
Vale. Ho sospitava. Que pesats amb això...
Gràcies igualment.
Et saludo des de Cat Nord 👋🏻

Le mar. 2 juil. 2019 à 17:49, Jofre Palau <notifications@github.com> a
écrit :

**Comment by jqandreu** [comment]
Veig que la sèrie es distribuirà a nivell mundial per Netflix. Suposo que la restricció fora de Catalunya és per això.
Moltes gràcies Azertixe, m'alegro que el plugin pugui ser útil
