### ISSUE TITLE
Torna a no estar accesible el contingut

### ISSUE THREAD

**Issue by Shut3n** [jqandreu/plugin.video.tv3.cat#16]
Bon día,

El contingut torna a estar inaccesible. Es pot entrar als menus principals del complement, pero ja no carrega les llistes de continguts ni pot connectar amb les emisions en directe. Tindrà res a veure amb la recent actualització en les apps oficials i la web de Televisió de Catalunya?

Salutacions i moltes gràcies per aquest complement.

**Comment by jqandreu** [comment]
Ho he provat en LibreElec i Windows i a mí sí em funciona tant directes com els programes a la carta. Només fallen les seccions Col·leccions i Avui destaquem per canvis a la web. Avui destaquem ha desaperagut de la web. Quina versió de Kodi i quin SO tens?

Salutacions

**Comment by Shut3n** [comment]
He provat a una Debian Buster tots dos Kodi 17.6 (del repo oficial de debian) i la 18.4 (del repositori https://deb-multimedia.org/). També ho he provat a Debian Sid en un altre equip i res tampoc. Acabe de comprovar que **els directes sí funcionen**, pero cap més dels altres. Els menús Programes ni Cercar donen resultats. Al pulsar Programes sí treu el llistat Sèries, Informatius, Documentals... Alfabètics... però d'ací ja no mostre més endins. No mai m'havia passat excepte quan van fer el canvis a la web l'any passat, he anat actualitzant el sistema i els kodis sense cap problema.

Acabe de comprovar q al **Kodi de l'Android funciona correctament** (Android 7 i Kodi 18), també **funciona en un equip amb Windows 10** (amb els mateixos complements instal·lats).

Podria ser algun complement (a Linux) causant conflicte o que no es troba al sistema? També algun certificat d'accéss web o mòdul de python? El script BeautifulSoup es a la versió 3.2.1. He intentat desactivar uns quants complements de tercers per si de cas i continua igual (inclosos els inputstream-adaptative i rtmp), també desinstal·lant i tornar a instal·lant aquest complement però igual.

Acabe de provar també esborrant la configuració de Kodi i començar-la des de zero (a Linux) sense èxit. Per el moment no se m'acut res més que provar, qualsevol cosa vaig comentant.

Salutacions

**Comment by jqandreu** [comment]
Pots provar un altre plugin semblant, per exemple Ted Talks?

**Comment by jqandreu** [comment]
El Debian Buster el tens a una Raspberry o PC? He trobat aquest fil, no se si pot ser el teu cas
https://forum.kodi.tv/showthread.php?tid=345076

**Comment by Shut3n** [comment]
Ted Talks funciona be. L'equip son dos PCs diferents (un amb l'S.O. de 32-bit i l'altre el de 64-bit). No tinc problema en l'arrancada, puc entrar al Kodi. Tot hi que em dona aquest missatge d'error a l'urllib3

_.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made.
Adding certificate verification is strongly advised.
See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)_

Només entrar a Kodi, sense començar a navegar. No se si podria estar relacionat
Cap altre missatge, només aquest

**Comment by jqandreu** [comment]
Pots enviarme el log despres d'entrar al plugin de tv3 i anar a algunes de les seccions que no funcionen? El meu email es msintes35@gmail.com

**Comment by jqandreu** [comment]
Crec que he trobar el fall. Es produeix un error en la libreria urllib2 de python quan intenta obrir un link https. Es produeix un error amb el protocol SSL, (wrong signature type). No tenc clar si és un error de Kodi o de la lliberia de python a  Debian. He enviat una pregunta al forum de Kodi a veure que em diuen

**Comment by jqandreu** [comment]
Confirmo que el fall és degut a que Debian Buster i Sid incorporen el paquet openssl 1.1.1. Openssl és l'encarregat de comprovar els certificats SSL de les webs. Aquesta versió és més restrictiva i no deixa connectar amb webs que tenguin certificats obsolets o que no utilitzin uns algoritmes més exigents. Per això alguns plugins funcionen i altres no. 

La solució és modificar el fitxer de configuració /etc/ssl/openssl.cnf per retornar al nivell de restricció anterior. 

Una altra solució seria demanar a tv3.cat que possi al dia els seus certificats SSL, per evitar més problemes

Aquí s'explica el problema i la solució. Ho he comprovat i funciona correctament. Basta modificar el paràmetre DEFAULT@SECLEVEL=2 i canviar el valor a DEFAULT@SECLEVEL=1

https://wiki.debian.org/ContinuousIntegration/TriagingTips/openssl-1.1.1

**Comment by calanor** [comment]
Confirmo que canviant el valor de DEFAULT@SECLEVEL de 2 a 1 funciona en Buster.  Només espero que això no faci que altres coses deixin de funcionar.
Gracies

**Comment by Shut3n** [comment]
Confirmo a buster i a sid funciona. Moltes gracies :)
