### ISSUE TITLE
Accés des de l'estranger

### ISSUE THREAD

**Issue by kurotorakun** [jqandreu/plugin.video.tv3.cat#17]
Bones jqandreu,

Abans de tot, felicitar-te per aquest plugin. Gràcies a ells som molts que podem gaudir de TV3 vivint fora de Catalunya. Per nosaltres és realment molt útil a més, ja que tenim un nen de 5 anys.

Hem observat que des del dia 4 de novembre (d'aquest any) no ens arriba a carregar cap canal.
A casa fem servir KODI 18 (Leia), en un raspberry pi amb Libreelec. 
No crec que sigui la versió de KODI, ja que fins ara ens funcionava correctament (amb l'habitual missatge de Emissió només a l'estat Espanyol on no es pot emetre material de tercers).

No he pogut provar si via VPN continua funcionant correctament.

Moltes gràcies,
K.

**Comment by jqandreu** [comment]
Moltes gràcies, m'alegra molt que pugui ser útil el plugin. 

Ja està resolt el problema, han fet canvis al servidor, han canviat les urls dels canals en directe. He enviat el plugin al repositori oficial, suposo que en unes hores s'actualitzarà automàticament. També podeu baixar la darrera versió directament des d'aqui

**Comment by kurotorakun** [comment]
Moltes gràcies!

He provat la nova versió al Kodi per Android i ja funciona novament. 
Aquesta nit la incorporaré a la raspberry. 

Moltes gràcies per la ràpida resposta i solució :) 
K.
