### ISSUE TITLE
compatibilitat amb Kodi 19 (matrix)

### ISSUE THREAD

**Issue by hoksilato2** [jqandreu/plugin.video.tv3.cat#18]
Hola Jqandreu!

Només avisar-te que el plugin no és compatible amb la versió alpha del Kodi 19 que incorpora les llibreries de Python 3.0.

Em fa l'efecte que per corregir el teu plugin només caldria canviar les versions de les dependències, però no n'estic del tot segur.

Si pots i tens temps podries fer-li una ullada. Les llibreries amb versió matrix son aquestes:

addon="script.module.beautifulsoup4" version="4.6.3+matrix.1"
addon="script.module.future" version="0.17.1+matrix.2"

L'error que dona al log és aquest:

> 2020-04-14 18:11:06.134 T:2484   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
> 2020-04-14 18:11:06.138 T:2484   ERROR: ExecuteAsync - Not executing non-existing script script.tv.show.next.aired
> 2020-04-14 18:11:06.492 T:10099   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <class 'ModuleNotFoundError'>
>                                             Error Contents: No module named 'BeautifulSoup'
>                                             Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/plugin.video.tv3.cat/addon.py", line 9, in <module>
>                                                 from resources.lib.ui.UI import UI
>                                               File "/storage/.kodi/addons/plugin.video.tv3.cat/resources/lib/ui/UI.py", line 4, in <module>
>                                                 from resources.lib.tv3cat.TV3cat import TV3cat
>                                               File "/storage/.kodi/addons/plugin.video.tv3.cat/resources/lib/tv3cat/TV3cat.py", line 7, in <module>
>                                                 from BeautifulSoup import BeautifulSoup
>                                             ModuleNotFoundError: No module named 'BeautifulSoup'
>                                             -->End of Python script error report<--
> 2020-04-14 18:11:06.858 T:10097   ERROR: GetDirectory - Error getting plugin://plugin.video.tv3.cat/
> 2020-04-14 18:11:06.870 T:2484   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tv3.cat/) failed

Tard o dora ens hi trobarem que deixarà de funcionar :)

Gràcies per tot!

**Comment by hoksilato2** [comment]
Ok perdona, veig que ja hi vas estar treballant per passar-lo a python 3. Doncs no sé que pot està passant :-D

**Comment by jqandreu** [comment]
El problema és amb les llibreries BeautifulSoup. Fins Kodi v18 inclou la versió 3 i la versió 4. Amb Kodi v19 només s'inclou la versió 4 de BeautifuSoup. Vaig intentar passar a la versió 4 però em donava problemas a Kodi v18. Com que Kodi v19 encara està en versió alpha esperaré si afegeixen la 3, si no ja cercaré una altra solució

**Comment by hoksilato2** [comment]
He intentat substituir la BeautifulSoup3 per la bs4 i si, també m'he trobat amb els problemes. Però els meus coneixements no donen per a més. A veure si afegeixen la 3 a la v19!

Gràcies per la resposta :-)

**Comment by cpages** [comment]
Acabo de provar la v19 Matrix i veig que això segueix igual. Pel que he estat llegint, no hi ha manera de fer un plugin compatible amb v19 i <=v18, no? Altres plugins se m'han actualitzat per v19 (i ja no van si torno a engegar v18). Entenc que ho fan amb 2 repositoris diferents, que suposo que és el que et caldrà? Merci!

**Comment by juanmah** [comment]
Ara Kodi 19 Matrix és oficial, s'actualitza i l'add-on no funciona.

**Comment by jqandreu** [comment]
Ja està actualitza l'addon a Kodi 19. La darrera versió 1.4.8 és compatible. Acabo d'enviar-lo al repositori oficial. Tardarà uns dies en aparèixer

**Comment by hoksilato2** [comment]
Fantástic @jqandreu!

Moltíssimes gràcies. Tanco el ticket!
