### ISSUE TITLE
Nomes 324 es posible veure en directe

### ISSUE THREAD

**Issue by koroki** [jqandreu/plugin.video.tv3.cat#25]
En la secció de canals en directes, només es possible veure el 324. Els altres canals no s'arriben a iniciar. Segurament els señors de tv3 han fet algun canvi en la web o en el codec.

**Comment by jofrep** [comment]
Confirmo les dues coses. 
Nomes es veu el 324 i la raó és el canvi de les URLs de l'streaming perquè les accedia directament al EPG del Kodi i cap funciona.

**Comment by jofrep** [comment]
La URL principal ha passat de 
http://directes-tv-es.ccma.cat/es/ngrp:tv3_web/playlist.m3u8
a
https://directes-tv-cat.ccma.cat/cat/ngrp:tv3_web/playlist.m3u8

**Comment by kurotorakun** [comment]
Bones jofrep,

Gràcies pel workaround, em funciona perfectament.
D'altra banda, em podríes confirmar quina és la URL per l'emissió internacional?
He vist que tampoc funciona (error 503).

Gràcies en avançat,
K.

**Comment by jofrep** [comment]
També l'han canviat :-(
De fet ha de ser la raò perquè l'aplicació de la TV Samsung no funciona

Veig que ara és: https://directes-tv-int.ccma.cat/int/ngrp:tvi_web/playlist.m3u8

**Comment by jqandreu** [comment]
Ja estan corregides les urls i enviat al repositori la nova versió.

**Comment by koroki** [comment]
Gracies!

**Comment by kurotorakun** [comment]
Moltes gràcies jqandreu!

Aquest add-on ens salva a tots els que estem fora de Catalunya :)

**Comment by jqandreu** [comment]
Un plaer poder ajudar. Només que no tinc gaire temps i només puc fer un manteniment molt bàsic. Pero veig que el plugin s'empra principalment ver veure els canals en directe. La navegació a l'arxiu de programes és molt lenta, no crec que ningú ho empri. Avui en dia tots els smart TV ja tenen l'app propia de TV3, molt més eficient

**Comment by koroki** [comment]
En el meu cas es que el meu smathTV es kodi en un miniPC amb linux. No tinc masses ganes de passar a una smathTV actuals on perds el control del teu dispositiu. Per això agraeixo molt la teva aplicació.
