### ISSUE TITLE
Els canals en directe no van

### ISSUE THREAD

**Issue by viric** [jqandreu/plugin.video.tv3.cat#3]
Hola, crec que l'únic contingut que em funciona és el del submenú de programes. Els canals en directe i els llistats de "més vistos", etc. del menú principal no em van. A algú altre li van? Faig servir la versió de master.

Per altra banda, és un plugim collonut. Moltes gràcies!

**Comment by jqandreu** [comment]
Fallava la secció "Avui destaquem". Ho he solucionat provisionalment, estic introduint altres millores. 
La resta, a mi em funciona tot, també els canals en directe. Pot ser que hagi estat un fall puntual del servidor.

Gràcies
