### ISSUE TITLE
Dels canals en directe nomes em funciona el 324

### ISSUE THREAD

**Issue by jrdfrncs** [jqandreu/plugin.video.tv3.cat#5]
Doncs be, com diu el titol, dels canals en directa el Kodi nomes es capac de obrir el canal 324. Alguna idea de perque? Alguna idea?

Podria ser que bloquessin l'stream perque visc al estranger?

Merci

**Comment by jqandreu** [comment]
Podria ser que hi hagi restriccions a altres paisos, pero no he trobat
gaire informacio. Pots veure els canals en directe des de la web de Tv3?
El dia 21/04/2016 22.10, "Jordi Frances" notifications@github.com va
escriure:

**Comment by jrdfrncs** [comment]
Si des de la web puc veure el feed de tv3.

**Comment by jrdfrncs** [comment]
Det fet acabo de fer la prova:

He tret les URL de el .py on les llistes, i les he passat per el VLC, i efectivament nomes carrega el 324, els altres canals em donen un "Can't open media".

**Comment by jrdfrncs** [comment]
He remenat una mica per la web de TV3 i he extret la URL del feed de TV3.
Aquesta sembla ser que si que el VLC me la obre:

http://ccma-tva-int-abertis-live.hls.adaptive.level3.net/int/ngrp:tv3_web/chunklist_b798000.m3u8

**Comment by jrdfrncs** [comment]
He mirat de desinstalar el plugin, editar el urls.py i reinstalar per tenir les noves URLs ...pero sembla ser que no he tingut sort. Te les deixo aqui a veure si tu hi pots fer res...potser afegir opcions als menus per els feeds internacionals

`url_directe_324 = 'http://ccma-tva-int-abertis-live.hls.adaptive.level3.net/int/ngrp:324_web/playlist.m3u8'

url_directe_tv3 = 'http://ccma-tva-int-abertis-live.hls.adaptive.level3.net/int/ngrp:tv3_web/playlist.m3u8'

url_directe_c33s3 = 'http://ccma-tva-int-abertis-live.hls.adaptive.level3.net/int/ngrp:c33_web/playlist.m3u8'

url_directe_esport3 = 'http://ccma-tva-int-abertis-live.hls.adaptive.level3.net/int/ngrp:es3_web/playlist.m3u8'`

**Comment by jqandreu** [comment]
Veig que les urls que has passat son per veure fora de l'estat. Ara mateix, pel canal Esport3, amb la url del plugin donen el partit de tenis de Nadal, mentre que a la teva url apareix el missatge "Emissió no disponible fora de l'estat espanyol".

Afegiré una opció per poder seleccionar les urls que has enviat. De quina pàgina has tret aquestes urls?

Per fer modificacions al plugin no fa falta que desinstalis i tornis a instalar. Nomes basta modificar el codi font i desar el fitxer. Si que és necessari sortir del video que estaves mirant i tornar al menu principal, o millor sortir del plugin, a la llista de plugins instalats, i tornar a entrar. Quan tornis al video, els canvis ja son efectius.

**Comment by jqandreu** [comment]
Per modificar les urls es té que fer al fitxer default.py. El fitxer resources/lib/urls.py era provisional, encara no s'utilitza. Pot ser que hagis modificat les urls dels canals en directe en aquest últim?

**Comment by jrdfrncs** [comment]
Si, les vaig canviar al urls.py i no al default.py. Les URLs les he tret posant la emisio en directe a la web a traves de navegador web i esnifejant paquets amb eines basades en PCAP per veure el contingut. I aixi he tret les URLs. Aixi que de cap pagina, sino que he rascat una mica. Doncs em modificare el default.py per provar i ja et dire com em va...aixi tenim info abans no facis les modificacions.

Tambe et fare un strings.xml per al noruec, no crec que ho faci servir gaire gent (som pocs els que parlem catala i noruec...pero ja que hi som vull colaborar una mica.

Salut

**Comment by jrdfrncs** [comment]
Ara mateix m'he afegit les entrades al menu amb les URLs noves. I funciona. Dema mirare de afegiri els strings perque posi TV3 (Internacional) al costat de les meves entrades.

Si que a vegades marca..."emisio no disponible" ...pero l'stream funciona, aixo ja es cosa de llicencies i el que TVC emet o no a l'estranger.

**Comment by jrdfrncs** [comment]
Doncs mira al final m'he animat i he afegit les entrades al menu, amb strings nous, per distingiro de les velles. Amb les URLs noves. He afegit traduccio al noruec bokmål, i he afegit al catala, castella i angles els strings que faltaven per les noves entrades de menu. Diria que tot funciona. A mi em funciona. 

Com que no tinc permisos per fer-te un push, te n'he fet un patch, aqui el tens.

[0001-Afegeix-les-URLs-per-als-streams-disponibles-desde-f.zip](https://github.com/jqandreu/plugin.video.tv3.cat/files/232849/0001-Afegeix-les-URLs-per-als-streams-disponibles-desde-f.zip)

**Comment by jqandreu** [comment]
Ok, moltes gràcies. Quan pugui ho miraré, faré el push i enviaré
l'actualització al repositori de Kodi

El dia 23 d’abril de 2016, 9:21, Jordi Frances notifications@github.com
ha escrit:

**Comment by jqandreu** [comment]
Tot be. Ja he fet el push i enviat l'actualització a Kodi
