### ISSUE TITLE
the plugin is not working in the new version Kripton

### ISSUE THREAD

**Issue by jordiliverpool** [jqandreu/plugin.video.tv3.cat#7]
Hello, my kodi updated to the latest version of kripton and now the add-on is not showing live channels anymore, I get a crash error but not good enough technically to see what happens

**Comment by jqandreu** [comment]
Hello. I've tested Kodi 17.1 in Windows and the live channels are showing without problems. What SO do you have?. Maybe changing codec video in advanced settings can help

**Comment by jordiliverpool** [comment]
Apologies,
I've checked again and it was my fault, somehow didn't setup properly the
new version. Now is working perfectly, great job, I can have again my
breakfast watching 324.
Thanks for the quick response

jordi
